#!/bin/sh
# Proper header for a Bash script.

DEPLOY_ADDRESS="/var/www/rive.senman.cz/app/"
DEPLOY_ROOT="/var/www/rive.senman.cz/"


echo "Start deploy ..."

echo "copy views"
scp -r ./app/views  ${DEPLOY_ADDRESS}
echo "copy controllers"
scp -r ./app/controllers  ${DEPLOY_ADDRESS}
echo "copy database"
scp -r ./app/database  ${DEPLOY_ADDRESS}
echo "copy models"
scp -r ./app/models  ${DEPLOY_ADDRESS}
echo "copy lang"
scp -r ./app/lang  ${DEPLOY_ADDRESS}
echo "copy filters"
scp ./app/filters.php  ${DEPLOY_ADDRESS}
echo "copy routes"
scp ./app/routes.php  ${DEPLOY_ADDRESS}
echo "copy composer.json"
scp ./composer.json  ${DEPLOY_ROOT}


echo "...  deploy finished."
